if has("gui_running")
    source $VIMRUNTIME/vimrc_example.vim
    source $VIMRUNTIME/gvimrc_example.vim
    if has("win16") || has("win32") || has("win64")
        source $VIMRUNTIME/mswin.vim
        behave mswin
        set guifont=Courier_New:h10:cANSI
    elseif has("unix")
        if !filereadable(expand("$HOME/.vim/plugin/airline.vim"))
            set guifont=Courier\ 10
        endif
    endif
    set go=
    " Manual viewer
    runtime ftplugin/man.vim
    nnoremap K :<C-U>exe "Man" v:count "<C-R><C-W>"<CR>
else
    source $VIMRUNTIME/vimrc_example.vim
    if has("win32") || has("win64")
        source $VIMRUNTIME/mswin.vim
        behave mswin
    endif
endif

runtime terminal-color-settings.vim
runtime tabspace-settings.vim
runtime airline-settings.vim
runtime fileencodings-settings.vim
runtime clangcomplete-settings.vim
runtime clangformat-settings.vim
"runtime javacomplete-settings.vim
"runtime eclim-settings.vim
runtime cscope-settings.vim
runtime keymappings-settings.vim
runtime nerdtree-settings.vim
runtime binary-settings.vim
runtime misc-settings.vim
